"""added contract address column in active gig

Revision ID: 50381bb2bed7
Revises: f40854a0925b
Create Date: 2025-03-23 01:09:12.525814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50381bb2bed7'
down_revision: Union[str, None] = 'f40854a0925b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_gigs', sa.Column('contract_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_active_gigs_contract_address'), 'active_gigs', ['contract_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_gigs_contract_address'), table_name='active_gigs')
    op.drop_column('active_gigs', 'contract_address')
    # ### end Alembic commands ###
