"""Create initial tables

Revision ID: 8f40078bf30a
Revises: 
Create Date: 2025-03-21 13:10:21.074528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f40078bf30a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('clerkId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('clerkId')
    )
    op.create_index(op.f('ix_users_clerkId'), 'users', ['clerkId'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerkId', sa.String(), nullable=True),
    sa.Column('worksNeeded', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('averageRating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clerkId'], ['users.clerkId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId')
    )
    op.create_index(op.f('ix_employer_details_id'), 'employer_details', ['id'], unique=False)
    op.create_table('freelancer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerkId', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('averageRating', sa.Float(), nullable=True),
    sa.Column('portfolioLinks', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['clerkId'], ['users.clerkId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId')
    )
    op.create_index(op.f('ix_freelancer_details_id'), 'freelancer_details', ['id'], unique=False)
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerkId', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profilePicture', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clerkId'], ['users.clerkId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId')
    )
    op.create_index(op.f('ix_user_details_id'), 'user_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_freelancer_details_id'), table_name='freelancer_details')
    op.drop_table('freelancer_details')
    op.drop_index(op.f('ix_employer_details_id'), table_name='employer_details')
    op.drop_table('employer_details')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerkId'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
