"""modified models.py to have a changed backref

Revision ID: ae7712c7868b
Revises: d5ae9c508af4
Create Date: 2025-03-23 00:30:03.523605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7712c7868b'
down_revision: Union[str, None] = 'd5ae9c508af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
