"""Update milestone_links JSON handling

Revision ID: f9c3feffa31c
Revises: 8553fbcd8693
Create Date: 2025-03-21 16:28:11.084592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c3feffa31c'
down_revision: Union[str, None] = '8553fbcd8693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
